### PR TITLE
Fixed eslint and prettier configuration

### LINKED ISSUE #45: Fix prettier and eslint on frontend

### PR DESCRIPTION
**Pull request by TudorStanca**
fixes #45

Established rules that prettier and eslint will apply in the project

### CODE REVIEW

**Review by the-horo — CHANGES_REQUESTED** [review]
fix conflicts

File: backend/Backend/Backend/Controllers/WeatherController.cs [hunk 1]
```diff
@@ -0,0 +1,25 @@
+﻿using Microsoft.AspNetCore.Mvc;
+
+namespace Backend.Controllers
+{
```
Comment (the-horo) [inline backend/Backend/Backend/Controllers/WeatherController.cs:4]:
```suggestion
namespace Backend.Controllers;
```

is much cleaner

File: backend/Backend/Backend/Controllers/WeatherController.cs [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+    [ApiController]
+    [Route("[controller]")]
+    public class WeatherController(ILogger<WeatherController> logger)
```
Comment (the-horo) [inline backend/Backend/Backend/Controllers/WeatherController.cs:7]: wtf is this controller?

Comment (TudorStanca) [reply backend/Backend/Backend/Controllers/WeatherController.cs:7]: 1. language
2. test controller for testing the logger

File: backend/Backend/Backend/Controllers/WeatherController.cs (hunk 1 above)
Comment (TudorStanca) [reply backend/Backend/Backend/Controllers/WeatherController.cs:4]: this file will be deleted, now it's only for api and logging testing

**Review by the-horo — APPROVED** [review]
poate nu mere
